

INSERT INTO USER (ID, USERNAME, PASSWORD, FIRSTNAME, LASTNAME, EMAIL, ENABLED, LASTPASSWORDRESETDATE)
 VALUES (4, 'kuba', '$2a$10$YClYl7fs33UDWxhmsKPy.eSMjx/MN54HqQNywba1tmIg4YBfyeSiy', 'Jakub', 'Wesolowski', 'kubawesolowski@me.com', 1, PARSEDATETIME('01-01-2019','dd-MM-yyyy'));

INSERT INTO AUTHORITY (ID, NAME) VALUES (1, 'ROLE_ADMIN');

INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES (4, 1);
